[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "aiphysicist"
authors = [{name = "cat123456", email = "eden@stu.pku.edu.cn"}]
dynamic = ["version", "description"]
